<?php

/**
 * @file
 * Primary module hooks for OTPLess module.
 */

/**
 * Implemented hook_page_attachments
 *
 * @param array $attachments
 * @return void
 */
function otpless_page_attachments(array &$attachments) {
  $config = \Drupal::config('otpless.settings');
  $is_enable = $config->get('active');
  if ($is_enable) {
    $attachments['#attached']['library'][] = 'otpless/otpless-auth';
    $attachments['#attached']['library'][] = 'otpless/otpless';
  }
}