# Schema for the configuration files of the OTPLess module.
otpless.settings:
  type: config_object
  label: 'OTPLess settings'
  mapping:
    active:
      type: string
      label: 'Enable OTPLess'
